import type {BodyModel} from "../app/body-atlas";
export const API="http://127.0.0.1:8000";
export type Method="source_model"|"assumption"|"derived"|"llm_hypothesis"|"llm_surrogate"|"hybrid"|"knowledge"|"unknown";
export type Source={id:string;title:string;url:string};
export type Parameter={name:string;value:number;unit:string;status:string;id?:string;low?:number;high?:number;rationale?:string};
export type Chemical={query:string;status:string;cid?:number;smiles?:string;formula?:string;molecular_weight?:number;structure_svg?:string;chembl_id?:string;retrieved_at?:string;activity_total?:number;sources:Source[];mechanisms:{mechanism_of_action?:string;action_type?:string;target_chembl_id?:string}[];activities:{source?:string;activity_id?:number;standard_type?:string;standard_relation?:string;standard_value?:string;standard_units?:string;target_pref_name?:string;target_organism?:string;assay_chembl_id?:string;document_chembl_id?:string}[]};
export type ReferenceScenario={event_index:number;label:string;entity:string;quantity:number;unit:string;basis:"reference";description:string};
export type EventInput={kind:string;label:string;entity?:string|null;quantity?:number|null;unit?:string|null;start_min:number;duration_min?:number|null;intensity_met?:number|null;missing:string[];route:string};
export type GraphNode={reference_scenario?:ReferenceScenario|null;id:string;label:string;group:string;stage:number;method:Method;method_label:string;description:string;body_system?:string;state_key:string|null;unit:string|null;cell_types:string[];equations:string[];parameters:Parameter[];sources:Source[];limitations:string[];compound?:Chemical;intervention?:EventInput;metric_id?:string;member_ids?:string[];process_id?:string;generated?:{level:string;entity:string;lower:number;upper:number;initial:number};linked_hypotheses?:{target:string;mechanism:string;limitation:string}[];execution?:{mode:string;effect_port?:string;driver?:string;gain:number;gain_low:number;gain_high:number;tau_min:number;rationale:string}|null};
export type GraphEdge={source:string;target:string;kind:string;label:string;source_state?:string;flux_key?:string;rate_coefficient?:number;unit?:string};
export type Metric={id:string;label:string;unit:string;values:number[]|null;baseline:number|null;method:Method;explanation:string};
export type Settings={horizon_min:number;body_mass_kg:number;activity_met:number;allow_assumptions:boolean;gastric_half_min:number;absorption_half_min:number;elimination_half_min:number;enable_llm_coupling:boolean;enable_body_network:boolean;llm_scale:number;sglt1_scale:number;glut2_scale:number;glut5_scale:number;sucrase_scale:number;glut4_scale:number;insulin_secretion_scale:number;model_parameters:Record<string,number>};
export type Interpretation={title:string;interventions:EventInput[];notes:string[]};
export type GeneratedModel={status:string;hash:string|null;states:number;processes:number;observations:{id:string;label:string;expression:string;unit:string;description:string;key:string}[];couplings?:{port:string;expression:string;description:string}[];parameters:(Parameter&{id:string;label:string;low:number;high:number})[];events:number[];checks:string[];reason?:string};
export type Run={reference_scenarios?:ReferenceScenario[];presentation_warning?:string;body?:BodyModel;run_id:string;title:string;created_at:string;plan_hash:string;plan:{settings:Settings;engine_version?:string};time:number[];traces:Record<string,number[]>;nodes:GraphNode[];edges:GraphEdge[];metrics:Metric[];compounds:Record<string,Chemical>;interpretation:Interpretation;summary:string;assumptions:string[];unmodeled:string[];warnings:string[];original_text?:string;is_preview?:boolean;generated?:GeneratedModel;event_coverage?:{event_index:number;label:string;native:boolean;generated:boolean;status:string}[];generation?:{failure_reason?:string|null;update?:{added_states:number;changed_observables:string[]}|null;planning_status?:string;native_complete?:boolean;cached:boolean;repaired:number;complete:boolean;rejected_attempts:{attempt:number;error:string}[]};coupling?:{hypothesis:number;status:string;nodes:string[];reason?:string;effect_port?:string;gain?:number}[];coverage:{integrated?:number;surrogates?:number;unresolved?:number;quantified:number;total:number;hypotheses:number;generated_states?:number;generated_processes?:number;events_modeled?:number;events_total?:number};validation:{solver:string;rtol:number;atol:number;nonnegative_check:boolean;balances:{name:string;max_error:number;unit:string;passed:boolean}[]};llm:{model:string;used:boolean;calls:number;replayed:boolean;elapsed_seconds:number}};
export type Progress={stage:number;message:string;fraction:number;phase?:string;elapsed_seconds?:number;phase_elapsed_seconds?:number;heartbeat?:boolean};
export const defaultSettings:Settings={horizon_min:240,body_mass_kg:70,activity_met:6,allow_assumptions:true,gastric_half_min:20,absorption_half_min:25,elimination_half_min:180,enable_llm_coupling:true,enable_body_network:true,llm_scale:1,sglt1_scale:1,glut2_scale:1,glut5_scale:1,sucrase_scale:1,glut4_scale:1,insulin_secretion_scale:1,model_parameters:{}};
export const methodLabels:Record<Method,string>={source_model:"Published model",assumption:"Assumed parameters",derived:"Definition / conversion",llm_hypothesis:"Unresolved pathway",llm_surrogate:"LLM approximation",hybrid:"Equations + LLM coupling",knowledge:"Database evidence",unknown:"Unmodeled"};
export const methodColors:Record<Method,string>={source_model:"#7fdccf",assumption:"#e6bb78",derived:"#82bcf5",llm_hypothesis:"#8d8a99",llm_surrogate:"#b5a1f3",hybrid:"#80dccf",knowledge:"#8ccfaf",unknown:"#8491a5"};
export function fmt(value:number|undefined|null,digits=1){return value==null||!Number.isFinite(value)?"—":Math.abs(value)>9999?value.toLocaleString("en-US",{maximumFractionDigits:0}):value.toLocaleString("en-US",{maximumFractionDigits:digits});}
export async function requestSimulation(text:string,settings:Settings,signal:AbortSignal,onProgress:(p:Progress)=>void,onInterpretation:(i:Interpretation)=>void,replayId?:string,onPreview?:(r:Run)=>void,rebuildModel=false):Promise<Run>{
 const response=await fetch(API+"/api/simulate",{method:"POST",headers:{"Content-Type":"application/json"},signal,body:JSON.stringify({text,settings,language:"en",replay_id:replayId??null,rebuild_model:rebuildModel})});
 if(!response.ok){let message="Please check the input conditions.";try{const body=await response.json() as {detail?:unknown};if(typeof body.detail==="string")message=/[가-힣]/.test(body.detail)?"Please check the input conditions.":body.detail;}catch{}throw Error(message);}
 const reader=response.body?.getReader();if(!reader)throw Error("Could not open the response stream.");
 const decoder=new TextDecoder();let buffer="";let result:Run|undefined;
 while(true){const {value,done}=await reader.read();buffer+=decoder.decode(value,{stream:!done});let boundary:number;while((boundary=buffer.indexOf("\n\n"))>=0){const event=buffer.slice(0,boundary);buffer=buffer.slice(boundary+2);const type=event.match(/^event: (.+)$/m)?.[1];const dataLine=event.match(/^data: (.+)$/m)?.[1];if(!dataLine)continue;const data=JSON.parse(dataLine);if(type==="progress")onProgress(data);if(type==="interpretation")onInterpretation(data);if(type==="preview")onPreview?.(data);if(type==="result")result=data;if(type==="error")throw Error(/[가-힣]/.test(data.message)?"Could not complete the simulation. Please try again.":data.message);}if(done)break;}
 if(!result)throw Error("No simulation result was received.");return result;
}
