"use client";
import {FlaskConical,ExternalLink,Network,ChevronRight} from "lucide-react";
import {Tabs,TabsContent,TabsList,TabsTrigger} from "@/components/ui/tabs";
import {ChartContainer} from "@/components/ui/chart";
import {LineChart,Line,XAxis,YAxis,Tooltip,ReferenceLine} from "recharts";
import {Run,GraphNode,methodColors,fmt} from "@/lib/simulation";

export function NodeInspector({run,node,timeIndex,onSelect}:{run:Run|null;node:GraphNode|null;timeIndex:number;onSelect:(id:string)=>void}){
 if(!run||!node)return <aside className="inspector"><div className="kicker">NODE INSPECTOR</div><div className="inspector-icon"><Network size={26}/></div><h2>작은 변화의 내부</h2><p className="intro">노드를 선택하면 관련 세포형, 분자, 수식과 실험 근거를 확인할 수 있습니다.</p><div className="inspector-row"><span>01</span>상태와 물질의 흐름</div><div className="inspector-row"><span>02</span>조직 · 세포 · 표적</div><div className="inspector-row"><span>03</span>수식과 파라미터</div><div className="inspector-row"><span>04</span>근거와 적용 범위</div><div className="inspector-bottom">계산된 값과 알려진 사실, LLM이 제안한 연결도 같은 수식에서 실행됩니다.</div></aside>;
 const values=node.state_key?run.traces[node.state_key]:null;const value=values?.[timeIndex];const chart=values?run.time.map((t,i)=>({time:t,value:values[i]})):[];
 const flows=run.edges.filter(e=>e.source===node.id||e.target===node.id);
 const chemical=node.compound;const siblings=run.nodes.filter(n=>n.group===node.group&&n.id!==node.id&&n.stage!==0);
 return <aside className="inspector live-inspector"><div className="kicker">NODE INSPECTOR</div><span className="method-tag" style={{color:methodColors[node.method],borderColor:methodColors[node.method]+"55"}}>{node.method_label}</span><h2>{node.label}</h2><p className="node-location">{node.group}</p><p className="intro">{node.description}</p>
 {value!=null&&<div className="node-reading"><strong>{fmt(value,3)}</strong><span>{node.unit}</span><small>t = {fmt(run.time[timeIndex])} min</small></div>}
 {chart.length>0&&<ChartContainer config={{value:{label:node.label,color:methodColors[node.method]}}} className="node-chart"><LineChart data={chart}><XAxis dataKey="time" tickFormatter={v=>`${Math.round(Number(v))}m`} minTickGap={35} axisLine={false} tickLine={false}/><YAxis hide domain={["auto","auto"]}/><Tooltip contentStyle={{background:"#151e29",border:"1px solid #364354",fontSize:13}} labelFormatter={v=>`${fmt(Number(v))} min`} formatter={v=>[`${fmt(Number(v),3)} ${node.unit}`,node.label]}/><ReferenceLine x={run.time[timeIndex]} stroke="#859aac" strokeDasharray="3 3"/><Line type="linear" dataKey="value" stroke={methodColors[node.method]} dot={false} strokeWidth={2} isAnimationActive={false}/></LineChart></ChartContainer>}
 <Tabs defaultValue="process" className="inspector-tabs"><TabsList className="inspector-tab-list"><TabsTrigger value="process">과정</TabsTrigger><TabsTrigger value="evidence">근거</TabsTrigger></TabsList><TabsContent value="process">
 {node.generated&&<div className="detail-block integrated-detail"><h3>자동 구성한 공유 상태</h3><dl><dt>해상도</dt><dd>{{molecule:"분자",cell:"세포",tissue:"조직",organ:"장기",system:"전신"}[node.generated.level]??node.generated.level}</dd><dt>대상</dt><dd>{node.generated.entity}</dd><dt>초기값</dt><dd>{fmt(node.generated.initial,3)}</dd><dt>선언된 범위</dt><dd>{fmt(node.generated.lower,3)} ~ {fmt(node.generated.upper,3)}</dd></dl><p>아래 식이 기존 모델과 같은 시간축에서 적분됩니다. 왼쪽 ‘이 모델의 계수’에서 가정을 바꾸고 재계산할 수 있습니다.</p></div>}
 {node.intervention&&<div className="detail-block"><h3>해석된 사건</h3><dl><dt>양</dt><dd>{fmt(node.intervention.quantity)} {node.intervention.unit}</dd><dt>시작</dt><dd>{fmt(node.intervention.start_min)} min</dd><dt>지속</dt><dd>{fmt(node.intervention.duration_min)} min</dd><dt>강도</dt><dd>{fmt(node.intervention.intensity_met)} MET</dd><dt>경로</dt><dd>{node.intervention.route}</dd></dl>{node.intervention.missing.map(s=><p className="amber-text" key={s}>미입력: {s}</p>)}</div>}
 {node.linked_hypotheses&&node.linked_hypotheses.length>0&&<div className="detail-block integrated-detail"><h3>이 수식에 연결된 LLM 경로</h3>{node.linked_hypotheses.map((h,i)=><div key={i}><b>{h.target}</b><p>{h.mechanism}</p></div>)}<small>{node.method==="llm_surrogate"?"상태를 적분해 연결 과정의 파라미터를 조절합니다.":"기존 실행 과정을 재사용합니다. 같은 효과를 중복 가산하지 않습니다."}</small></div>}
 {node.execution?.mode==="surrogate"&&<div className="detail-block"><h3>근사 연결</h3><p>{node.execution.rationale}</p><p>계수 범위 {fmt(node.execution.gain_low,2)} ~ {fmt(node.execution.gain_high,2)} · 시간상수 {fmt(node.execution.tau_min)}분</p></div>}
 {flows.length>0&&<div className="detail-block"><h3>연결된 과정 · 현재 흐름</h3>{flows.slice(0,10).map((e,i)=>{const outward=e.source===node.id;const other=run.nodes.find(n=>n.id===(outward?e.target:e.source));const rate=e.flux_key?run.traces[e.flux_key]?.[timeIndex]:e.source_state&&e.rate_coefficient!=null?(run.traces[e.source_state]?.[timeIndex]??0)*e.rate_coefficient:null;return <button className="sibling-button flow-detail" key={i} onClick={()=>onSelect(other?.id??node.id)}><span>{outward?"→":"←"} {other?.label}<small>{e.label}</small></span><b>{rate!=null?`${fmt(rate,3)} ${e.unit??""}`:""}</b></button>})}</div>}
 {node.cell_types.length>0&&<div className="detail-block"><h3>관련 세포형</h3><div className="cell-chips">{node.cell_types.map(c=><span key={c}>{c}</span>)}</div></div>}
 {node.equations.length>0&&<div className="detail-block"><h3>계산식</h3>{node.equations.map(e=><code className="equation" key={e}>{e}</code>)}</div>}
 {node.parameters.length>0&&<div className="detail-block"><h3>파라미터</h3>{node.parameters.map(p=><div className="parameter-row" key={p.name}><span>{p.name}<small>{p.status==="source_model"?"원본 모델":p.status==="user_input"?"설정값":p.status==="llm_estimate"?"LLM 근사 계수":"가정"}</small></span><b>{fmt(p.value,4)}<small>{p.unit}</small></b></div>)}</div>}
 {chemical?.status==="resolved"&&<div className="detail-block"><h3>분자 정보 · RDKit</h3>{chemical.structure_svg&&<img className="molecule-image" src={`data:image/svg+xml;charset=utf-8,${encodeURIComponent(chemical.structure_svg)}`} alt={`${chemical.query} 분자 구조`}/>}<dl><dt>분자식</dt><dd>{chemical.formula}</dd><dt>분자량</dt><dd>{chemical.molecular_weight} g/mol</dd><dt>PubChem CID</dt><dd>{chemical.cid}</dd></dl><code className="smiles">{chemical.smiles}</code></div>}
 {siblings.length>0&&<div className="detail-block"><h3>같은 그룹의 과정</h3>{siblings.map(s=><button className="sibling-button" key={s.id} onClick={()=>onSelect(s.id)}>{s.label}<ChevronRight size={14}/></button>)}</div>}
 </TabsContent><TabsContent value="evidence"><div className="detail-block"><h3>참조 자료</h3>{node.sources.length===0?<p className="muted">이 노드에 직접 연결된 실험 자료가 없습니다.</p>:node.sources.map(s=><a className="source-link" key={s.id} href={s.url} target="_blank" rel="noreferrer">{s.title}<ExternalLink size={13}/></a>)}</div>
 {chemical&&<div className="detail-block"><h3>조회된 작용 기전</h3>{chemical.mechanisms.length?chemical.mechanisms.map((m,i)=><div className="mechanism-card" key={i}><b>{m.action_type}</b><p>{m.mechanism_of_action}</p><small>{m.target_chembl_id}</small></div>):<p className="muted">기전 레코드가 없거나 조회에 실패했습니다. 결합하지 않는다는 의미가 아닙니다.</p>}
 <h3>활성 실험 표본</h3><p className="fine-print">최대 20개 조회 표본. Kd·Ki·IC50·EC50는 서로 다른 측정입니다. 아래 값은 현재 몸의 결합률이 아닙니다.</p>{chemical.activities.slice(0,12).map((a,i)=><div className="assay-card" key={a.activity_id??i}><b>{a.target_pref_name||"표적 정보 없음"}</b><span>{a.standard_type} {a.standard_relation} {a.standard_value} {a.standard_units}</span><small>{a.target_organism} · {a.source??"ChEMBL"} {a.assay_chembl_id}</small></div>)}{chemical.retrieved_at&&<small className="muted">조회: {new Date(chemical.retrieved_at).toLocaleDateString("ko-KR")}</small>}</div>}
 </TabsContent></Tabs><div className="limit-box"><FlaskConical size={17}/><div><b>적용 범위</b>{(node.limitations.length?node.limitations:["모델에서 표현한 해상도와 연결 범위 내에서 해석하세요."]).map(l=><p key={l}>{l}</p>)}</div></div></aside>
}
