"use client";
import {useMemo,useState} from "react";
import {Plus,Minus,Maximize2,Layers3} from "lucide-react";
import {Button} from "@/components/ui/button";
import {GraphNode,GraphEdge,Run,methodColors,fmt} from "@/lib/simulation";

export function PhysiologyGraph({systemFilter="all",onSystemFilter,run,stage,timeIndex,selected,onSelect,detail,onDetail,playing}:{systemFilter?:string;onSystemFilter?:(id:string)=>void;run:Run;stage:number;timeIndex:number;selected:string|null;onSelect:(id:string)=>void;detail:boolean;onDetail:()=>void;playing:boolean}){
 const [zoom,setZoom]=useState(1);
 const graph=useMemo(()=>{
  let nodes=run.nodes.filter(n=>n.stage<=stage);let edges=run.edges;
  if(systemFilter!=="all"){const focus=new Set(run.nodes.filter(n=>n.body_system===systemFilter).map(n=>n.id));const neighbors=new Set(edges.filter(e=>focus.has(e.source)||focus.has(e.target)).flatMap(e=>[e.source,e.target]));nodes=nodes.filter(n=>focus.has(n.id)||neighbors.has(n.id)||n.stage===0);}
  const mapping:Record<string,string>={};
  if(!detail){const groups=new Map<string,GraphNode[]>();for(const n of nodes){const key=n.body_system&&n.stage===3&&systemFilter==="all"?`body-system/${n.body_system}`:n.stage===0||n.stage===4||n.method==="llm_hypothesis"||n.method==="llm_surrogate"||n.process_id?n.id:`${n.stage}/${n.group}`;groups.set(key,[...(groups.get(key)??[]),n]);}nodes=[...groups].map(([key,members])=>{members.forEach(n=>mapping[n.id]=key);return members.length===1?{...members[0],id:key,member_ids:[members[0].id]}:{...members[0],id:key,label:members[0].group+([""," · 흡수"," · 순환"," · 과정",""][members[0].stage]),state_key:null,unit:null,member_ids:members.map(n=>n.id)};});edges=edges.map(e=>({...e,source:mapping[e.source]??e.source,target:mapping[e.target]??e.target})).filter(e=>e.source!==e.target);}
  const priority=["transport:sglt1","transport:glut2","transport:glut5","glucose"];
  const lanes=Array.from({length:5},(_,i)=>nodes.filter(n=>n.stage===i).sort((a,b)=>i===2?(priority.indexOf(a.member_ids?.[0]??a.id)<0?99:priority.indexOf(a.member_ids?.[0]??a.id))-(priority.indexOf(b.member_ids?.[0]??b.id)<0?99:priority.indexOf(b.member_ids?.[0]??b.id)):0));const maxRows=Math.max(3,...lanes.map(l=>l.length));const height=Math.max(450,maxRows*116+88),width=1120;
  const positions:Record<string,{x:number;y:number}>={};lanes.forEach((list,col)=>list.forEach((n,row)=>positions[n.id]={x:24+col*220,y:60+row*116}));
  const ids=new Set(nodes.map(n=>n.id));return{nodes,edges:edges.filter(e=>ids.has(e.source)&&ids.has(e.target)).filter((e,i,a)=>a.findIndex(x=>x.source===e.source&&x.target===e.target&&x.kind===e.kind)===i),positions,width,height};
 },[run,stage,detail,systemFilter]);
 const active=new Set(graph.nodes.filter(n=>n.id===selected||n.member_ids?.includes(selected??"")).map(n=>n.id));
 const adjacent=new Set(graph.edges.filter(e=>active.has(e.source)||active.has(e.target)).flatMap(e=>[e.source,e.target]));
 return <div className="live-graph"><div className="graph-tools">{systemFilter!=="all"&&<span className="graph-scope-label">{run.body?.systems.find(s=>s.id===systemFilter)?.label??"순환"}<button onClick={()=>onSystemFilter?.("all")}>전체</button></span>}<Button variant="outline" size="sm" onClick={onDetail}><Layers3 size={14}/>{detail?"장기별로 묶기":"세포·분자 펼치기"}</Button><div><Button variant="ghost" size="icon" aria-label="그래프 축소" onClick={()=>setZoom(v=>Math.max(.65,v-.15))}><Minus size={16}/></Button><span>{Math.round(zoom*100)}%</span><Button variant="ghost" size="icon" aria-label="그래프 확대" onClick={()=>setZoom(v=>Math.min(1.75,v+.15))}><Plus size={16}/></Button><Button variant="ghost" size="icon" aria-label="그래프 배율 초기화" onClick={()=>setZoom(1)}><Maximize2 size={15}/></Button></div></div>
 <div className="graph-viewport"><svg className="physiology-svg" viewBox={`0 0 ${graph.width} ${graph.height}`} style={{width:`${zoom*100}%`,minWidth:Math.round(900*zoom)}} role="group" aria-label="생리 과정 그래프"><defs><marker id="arrow-flow" markerWidth="6" markerHeight="6" refX="5" refY="3" orient="auto"><path d="M0,0 L6,3 L0,6" fill="#609e98"/></marker><marker id="arrow-regulation" markerWidth="6" markerHeight="6" refX="5" refY="3" orient="auto"><path d="M0,0 L6,3 L0,6" fill="#b39be6"/></marker></defs>
 {["입력 사건","진입 · 자극","공유 상태","조직 · 세포","전신 관측값"].map((s,i)=><text key={s} x={24+i*220} y={26} className="lane-label">{s}</text>)}
 {graph.edges.map((e,i)=>{const a=graph.positions[e.source],b=graph.positions[e.target];const forward=b.x>a.x;const ax=a.x+190,ay=a.y+43,bx=b.x,by=b.y+43;const path=forward?`M${ax},${ay} C${ax+70},${ay} ${bx-70},${by} ${bx},${by}`:`M${ax},${ay} C${ax+45},${ay+75} ${bx-40},${by+75} ${bx},${by}`;const hypothesis=e.kind==="hypothesis";const related=active.has(e.source)||active.has(e.target);const rate=e.flux_key?(run.traces[e.flux_key]?.[timeIndex]??null):e.source_state&&e.rate_coefficient!=null?(run.traces[e.source_state]?.[timeIndex]??0)*e.rate_coefficient:null;return <g key={`${e.source}-${e.target}-${i}`} opacity={selected && !related ? 0.85 : 1}><path d={path} fill="none" stroke={e.kind==="coupling"?"#b5a1f3":hypothesis?"#6c637f":related?"#7fdccf":"#416561"} strokeWidth={related?2:1.3} strokeDasharray={hypothesis||e.kind==="regulation"?"5 5":undefined} markerEnd={`url(#arrow-${hypothesis?"regulation":"flow"})`} className={playing&&rate!=null&&rate>.01?"flowing-edge":""}/>{related&&<text x={(ax+bx)/2} y={(ay+by)/2-9} className="edge-label">{rate!=null?`${fmt(rate,2)} ${e.unit}`:e.label}</text>}</g>})}
 {graph.nodes.map(n=>{const p=graph.positions[n.id],isSelected=active.has(n.id),color=methodColors[n.method],value=n.state_key?run.traces[n.state_key]?.[timeIndex]:null;return <g key={n.id} transform={`translate(${p.x},${p.y})`} role="button" tabIndex={0} aria-label={`${n.label}, ${n.method_label}`} onClick={()=>onSelect(n.member_ids?.[0]??n.id)} onKeyDown={e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();onSelect(n.member_ids?.[0]??n.id);}}} className="graph-node" opacity={selected && !isSelected && !adjacent.has(n.id) ? 0.7 : 1}>
 <rect width={190} height={89} rx={10} fill={isSelected?"#1a302f":"#151f2b"} stroke={isSelected?"#88e8d9":color+"80"} strokeWidth={isSelected?2:1}/><rect x={0} y={24} width={3} height={39} rx={1} fill={color}/><text x={15} y={22} fill={color} className="svg-node-method">{n.method_label}</text><text x={15} y={47} className="svg-node-name">{n.label.length>15?n.label.slice(0,14)+"…":n.label}</text><text x={15} y={72} className="svg-node-value">{value!=null?`${fmt(value,2)} ${n.unit??""}`:n.member_ids&&n.member_ids.length>1?`${n.member_ids.length}개 세부 과정`:n.method==="unknown"?"정량 연결 없음":n.method==="llm_hypothesis"?"실행 연결 보류":n.group}</text>
 </g>})}</svg></div><div className="graph-legend"><span><i style={{background:"#7fdccf"}}/>기존 모델</span><span><i style={{background:"#e6bb78"}}/>가정 기반 계산</span><span><i style={{background:"#b5a1f3"}}/>LLM 근사 계산</span><span><i style={{background:"#8491a5"}}/>미모델링</span></div></div>
}
